### ISSUE TITLE
libvorbis_64

### ISSUE THREAD

**Issue by NobodyOffcal** [xenesense/xenesense-loader#1]
libvorbis_64 how to use ?

**Comment by xenesense** [comment]
what ?

**Comment by NobodyOffcal** [comment]
how can i use injector

**Comment by xenesense** [comment]
if you are already a fucking retard and want to skid this please LEARN THE LANGUAGE FFS. Like bro how can you be this fucking retarded and OPEN AN ISSUE BECAUSE UR DUMBASS IS TOO RETARDED TO USE SOMETHING.
